# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-pv-ssd
spec:
  capacity:
    storage: 10Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /hans_data
    server: 10.220.52.66

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filestore-pvc-ssd
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
  volumeName: filestore-pv-ssd
