# **************************************************
# Copyright (c) 2026, Mayank Mishra
# **************************************************

profiles:
  mayank-data:
    storage_provider:
      type: gcs
      options:
        base_path: mayank-data
