# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mayank-data-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
