# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

apiVersion: batch/v1
kind: Job
metadata:
  name: mayank-job
spec:
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: gcs-access
      containers:
      - name: mayank-job
        image: ghcr.io/open-lm-engine/data:latest
        command: ["sleep", "infinity"]
        resources:
          requests:
            cpu: "500m"
            memory: "8Gi"
          limits:
            cpu: "1"
            memory: "8Gi"
        volumeMounts:
        - name: gcs-volume
          mountPath: /data
      volumes:
      - name: gcs-volume
        persistentVolumeClaim:
          claimName: mayank-data-pvc
      restartPolicy: Never
  backoffLimit: 0
