# **************************************************
# Copyright (c) 2025, Mayank Mishra
# **************************************************

datasets:
  - class_name: MegatronDataset
    data_name: Megatron
    data_sampling_ratio: 1
    class_args:
      eval_steps: 2
      num_workers: 16
      data_cache_path: /data/cache_jyo/
      data_path:
        - /data/dolma_merged/merged_text
      split: 99.5,0.5,0
      sequence_length: 4096

tokenizer_args:
  tokenizer_name: allenai/OLMo-3-1025-7B

kernel_args:
  kernels:
    - rnn
    - gru
    - flash_attention_3

model_args:
  pretrained_config:
    initializer_range: 0.02
    layer_norm_epsilon: 1e-05
    model_type: gpt_base
    normalization_function: rmsnorm
    position_embedding_type: rope
    hidden_size: 768
    num_layers: 12
    m_width: 1
    m_emb: 1
    m_residual: 1
    init_method: mup_fan_in
    embedding_init_method: normal
    use_depth_scaled_init: false
    bos_token_id: 100257
    eos_token_id: 100257
    pad_token_id: 100277
    vocab_size: 100278
    max_position_embeddings: 4096
    sequence_mixer_blocks:
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
      - sequence_mixer_type: softmax_attention
        num_attention_heads: 16
        num_key_value_heads: 16
        add_bias: false
    mlp_blocks:
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
      - activation_function: silu
        mlp_type: DeltaMLP
        add_bias: false
        intermediate_size: 1984
        num_ranks: 44
        num_heads: 16
        use_v_proj: false
        use_q_l2norm: false
        use_shortconv: true
        use_mlp_stream: false
        use_input_gate: true
        use_output_gate: false
        use_output_norm: true
        use_zero_init_k: false
        allow_neg_eigval: false
        kernel_size: 4
        value_scale: 0.025
        use_v_silu: false
        use_tied_beta: false
        use_decay_beta: false
        use_head_norm: true
  efficient_initialization: true

tuning_args:
  tuning_method: pretraining

save_args:
  save_path: /data/checkpoints_jyo/hyperball-test
  save_interval: 10000

logging_args:
  log_interval: 10
  experiments_tracker_name: wandb
  wandb_args:
    project: deltamlp-opt-short
    name: hyperball-test

training_parameters:
  num_training_steps: 8000
  eval_interval: 2000
  micro_batch_size: 8
  gradient_accumulation_steps: 2
  eval_during_training: true

optimizer_args:
  params_group_method: hyperball
  class_name: HyperballAdamW
  class_args:
    lr: 1.3e-2
    weight_decay: 0.1
    betas:
      - 0.9
      - 0.95
    eps: 1e-10

lr_scheduler_args:
  lr_decay_style: cosine
  num_warmup_steps: 800
  num_constant_steps: 0
  num_decay_steps: 7200

mixed_precision_args:
  dtype: bf16

distributed_args:
  stage: 0
  torch_compile: true
